### ISSUE TITLE
Add method to close current window (but not the whole browser)

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1016]
## The problem
I want to close a current window/tab (but leave other windows/tabs opened).
Selenide has method `Selenide.close()`, but it close the whole browser/webdriver. At least name of this method is misleading.

**Comment by asolntsev** [comment]
done in PR https://github.com/selenide/selenide/pull/1017

**Comment by kiritoqa** [comment]
Method Selenide.closeWindow() close all windows, he doesn't close the only tab.
Selenide.open()
Selenide.click()
Selenide.switchTo().window(1);
Selenide.closeWindow()

**Comment by asolntsev** [comment]
@kiritoqa Why do you think so? I just tried - method `Selenide.closeWindow()` closes only the current window. 
Please provide some code sample for reproducing the issue.

**Comment by ngavaleshko** [comment]
hey, the problem is still exist. I need to use it in test with data provider and after each data set just close the tab.
During the test :
- the new tab was opened
- driver was switched to new tab
- assertion was done
- browser was closed
after that the browsers stars again and doing another data set. And is closing after each data set.

    @Test(dataProvider = "dp1")
    void solutionCardLinksTest(String expectedUrl, SelenideElement element) {
        element.click();
        switchTo().window(1);
        Selenide.webdriver().shouldHave(url(expectedUrl));
        Selenide.closeWindow();

**Comment by kiritoqa** [comment]
I solved the problem with this method.
        switchTo().window(1);
        Selenide.closeWindow();
        switchTo().window(0);
        Assert.assertTrue(actualTitle.contains(title), String.format("Invalid Url expected %s but found %s",title, actualTitle));
